[nixpkgs]
src.cmd = "curl -s -o /dev/null -w '%{url_effective}' -L --range 0-0 https://channels.nixos.org/nixos-unstable/nixexprs.tar.zst | grep -oP 'nixos-\\K[^/]+(?=/nixexprs)'"
fetch.tarball = "https://releases.nixos.org/nixos/unstable/nixos-$ver/nixexprs.tar.zst"

[mnw]
src.git = "https://github.com/Gerg-L/mnw"
fetch.tarball = "https://github.com/Gerg-L/mnw/archive/$ver.tar.gz"
