[tack]
recomposable = true

[shorturls]
gh = "github:{path}"
nixpkgs = "https://channels.nixos.org/{path}/nixexprs.tar.xz"

[inputs.nixpkgs]
url = "nixpkgs:nixos-unstable"

[inputs.mnw]
url = "gh:Gerg-L/mnw"

[inputs.base46]
url = "gh:AvengeMedia/base46"
type = "fetch"
