# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mnw = {
    pname = "mnw";
    version = "0151d9fa87992cbeb67c86616fb9170dcec830b6";
    src = fetchTarball {
      url = "https://github.com/Gerg-L/mnw/archive/0151d9fa87992cbeb67c86616fb9170dcec830b6.tar.gz";
      sha256 = "sha256-HRn4O1X2ShYtbq5Egji72/aemyc2cIQicjRZD9hBqM8=";
    };
    date = "2026-07-15";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "6774f7bc253789b113a4f39285dc0fa100abeacc";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/6774f7bc253789b113a4f39285dc0fa100abeacc.tar.gz";
      sha256 = "sha256-MYiI+CzL0tuWgRPjGsKCDHqYs2T3OzMlMQWOYWG0qso=";
    };
    date = "2026-09-22";
  };
}
