# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mnw = {
    pname = "mnw";
    version = "0151d9fa87992cbeb67c86616fb9170dcec830b6";
    src = fetchTarball {
      url = "https://github.com/Gerg-L/mnw/archive/0151d9fa87992cbeb67c86616fb9170dcec830b6.tar.gz";
      sha256 = "sha256-HRn4O1X2ShYtbq5Egji72/aemyc2cIQicjRZD9hBqM8=";
    };
    date = "2026-07-15";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "44a91898084f46797b5fac650c7e8c9ac38c43d4";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/44a91898084f46797b5fac650c7e8c9ac38c43d4.tar.gz";
      sha256 = "sha256-Ft/BRnIqw1MywFoXydKobjjWmDFgDdYtSpJliE8+yUw=";
    };
    date = "2026-09-20";
  };
}
