# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  mnw = {
    pname = "mnw";
    version = "0151d9fa87992cbeb67c86616fb9170dcec830b6";
    src = fetchTarball {
      url = "https://github.com/Gerg-L/mnw/archive/0151d9fa87992cbeb67c86616fb9170dcec830b6.tar.gz";
      sha256 = "sha256-HRn4O1X2ShYtbq5Egji72/aemyc2cIQicjRZD9hBqM8=";
    };
    date = "2026-07-15";
  };
  nixpkgs = {
    pname = "nixpkgs";
    version = "8ce4ef6cb6f871616146b9fe26d2a5ae594e94fe";
    src = fetchTarball {
      url = "https://github.com/NixOS/nixpkgs/archive/8ce4ef6cb6f871616146b9fe26d2a5ae594e94fe.tar.gz";
      sha256 = "sha256-xB8mKMOx1IA9vTDNLmJZ6n4wCMq/cuWBBOzGCRnqxrU=";
    };
    date = "2026-09-10";
  };
}
